<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $karyawanData = [
            // Admin - Chief Executive Officer
            [
                'nip'                    => 'ADMIN001',
                'email'                  => 'admin@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Budi',
                'nama_belakang'          => 'Santoso',
                'nama_lengkap'           => 'Budi Santoso',
                'role'                   => 'admin',
                'jabatan'                => 'Chief Executive Officer',
                'jabatan_lainnya'        => null,
                'status'                 => 'Permanent',
                'nomor_telepon'          => '081200000001',
                'jenis_kelamin'          => 'L',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Jakarta',
                'tanggal_lahir'          => '1985-03-15',
                'status_pernikahan'      => 'Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Universitas Indonesia',
                'jurusan'                => 'Teknik Informatika',
                'tahun_lulus'            => 2007,
                'alamat'                 => 'Jl. Sudirman No. 1, Jakarta Pusat',
                'nik'                    => '3171010000000001',
                'npwp'                   => '12.345.678.9-012.000',
                'tanggal_bergabung'      => '2020-01-01',
                'nama_kontak_darurat'    => 'Siti Santoso',
                'telepon_kontak_darurat' => '081200000011',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567890',
            ],

            // HR - Chief Operating Officer
            [
                'nip'                    => 'HR001',
                'email'                  => 'hr@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Dewi',
                'nama_belakang'          => 'Rahayu',
                'nama_lengkap'           => 'Dewi Rahayu',
                'role'                   => 'hr',
                'jabatan'                => 'Chief Operating Officer',
                'jabatan_lainnya'        => null,
                'status'                 => 'Permanent',
                'nomor_telepon'          => '081200000002',
                'jenis_kelamin'          => 'P',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Bandung',
                'tanggal_lahir'          => '1990-07-22',
                'status_pernikahan'      => 'Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Universitas Padjadjaran',
                'jurusan'                => 'Psikologi',
                'tahun_lulus'            => 2012,
                'alamat'                 => 'Jl. Asia Afrika No. 10, Bandung',
                'nik'                    => '3273010000000002',
                'npwp'                   => '12.345.678.9-012.001',
                'tanggal_bergabung'      => '2021-03-01',
                'nama_kontak_darurat'    => 'Ahmad Rahayu',
                'telepon_kontak_darurat' => '081200000012',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567891',
            ],

            // Karyawan 1 — Permanent — Finance
            [
                'nip'                    => 'EMP0001',
                'email'                  => 'azkiya@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Azkiya',
                'nama_belakang'          => 'Zahra',
                'nama_lengkap'           => 'Azkiya Zahra',
                'role'                   => 'karyawan',
                'jabatan'                => 'Finance',
                'jabatan_lainnya'        => null,
                'status'                 => 'Permanent',
                'nomor_telepon'          => '081200000003',
                'jenis_kelamin'          => 'P',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Yogyakarta',
                'tanggal_lahir'          => '1995-04-10',
                'status_pernikahan'      => 'Belum Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Universitas Gadjah Mada',
                'jurusan'                => 'Akuntansi',
                'tahun_lulus'            => 2017,
                'alamat'                 => 'Jl. Malioboro No. 5, Yogyakarta',
                'nik'                    => '3404010000000003',
                'npwp'                   => '12.345.678.9-012.002',
                'tanggal_bergabung'      => '2022-01-10',
                'nama_kontak_darurat'    => 'Zahra Sari',
                'telepon_kontak_darurat' => '081200000013',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567892',
            ],

            // Karyawan 2 — Permanent — Videographer
            [
                'nip'                    => 'EMP0002',
                'email'                  => 'rizky@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Rizky',
                'nama_belakang'          => 'Firmansyah',
                'nama_lengkap'           => 'Rizky Firmansyah',
                'role'                   => 'karyawan',
                'jabatan'                => 'Videographer',
                'jabatan_lainnya'        => null,
                'status'                 => 'Permanent',
                'nomor_telepon'          => '081200000004',
                'jenis_kelamin'          => 'L',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Surabaya',
                'tanggal_lahir'          => '1993-09-18',
                'status_pernikahan'      => 'Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Institut Teknologi Sepuluh Nopember',
                'jurusan'                => 'Teknik Elektro',
                'tahun_lulus'            => 2015,
                'alamat'                 => 'Jl. Pemuda No. 30, Surabaya',
                'nik'                    => '3578010000000004',
                'npwp'                   => '12.345.678.9-012.003',
                'tanggal_bergabung'      => '2021-07-01',
                'nama_kontak_darurat'    => 'Rina Firmansyah',
                'telepon_kontak_darurat' => '081200000014',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567893',
            ],

            // Karyawan 3 — Contract — Creative Writer
            [
                'nip'                    => 'EMP0003',
                'email'                  => 'ani@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Ani',
                'nama_belakang'          => 'Rahmawati',
                'nama_lengkap'           => 'Ani Rahmawati',
                'role'                   => 'karyawan',
                'jabatan'                => 'Creative Writer',
                'jabatan_lainnya'        => null,
                'status'                 => 'Contract',
                'nomor_telepon'          => '081200000005',
                'jenis_kelamin'          => 'P',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Semarang',
                'tanggal_lahir'          => '1997-12-05',
                'status_pernikahan'      => 'Belum Menikah',
                'pendidikan_terakhir'    => 'D3',
                'pendidikan_terakhir_new'=> 'D3',
                'universitas'            => 'Universitas Diponegoro',
                'jurusan'                => 'Manajemen',
                'tahun_lulus'            => 2019,
                'alamat'                 => 'Jl. Pandanaran No. 15, Semarang',
                'nik'                    => '3374010000000005',
                'npwp'                   => '12.345.678.9-012.004',
                'tanggal_bergabung'      => '2023-02-01',
                'nama_kontak_darurat'    => 'Hadi Rahmawati',
                'telepon_kontak_darurat' => '081200000015',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567894',
            ],

            // Karyawan 4 — Contract — Social Media Manager
            [
                'nip'                    => 'EMP0004',
                'email'                  => 'dimas@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Dimas',
                'nama_belakang'          => 'Prasetyo',
                'nama_lengkap'           => 'Dimas Prasetyo',
                'role'                   => 'karyawan',
                'jabatan'                => 'Social Media Manager',
                'jabatan_lainnya'        => null,
                'status'                 => 'Contract',
                'nomor_telepon'          => '081200000006',
                'jenis_kelamin'          => 'L',
                'agama'                  => 'Kristen',
                'tempat_lahir'           => 'Medan',
                'tanggal_lahir'          => '1996-06-25',
                'status_pernikahan'      => 'Belum Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Universitas Sumatera Utara',
                'jurusan'                => 'Sistem Informasi',
                'tahun_lulus'            => 2018,
                'alamat'                 => 'Jl. Gatot Subroto No. 8, Medan',
                'nik'                    => '1271010000000006',
                'npwp'                   => '12.345.678.9-012.005',
                'tanggal_bergabung'      => '2023-08-15',
                'nama_kontak_darurat'    => 'Linda Prasetyo',
                'telepon_kontak_darurat' => '081200000016',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567895',
            ],

            // Karyawan 5 — Outsource — Business Development
            [
                'nip'                    => 'EMP0005',
                'email'                  => 'sari@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Sari',
                'nama_belakang'          => 'Indah Lestari',
                'nama_lengkap'           => 'Sari Indah Lestari',
                'role'                   => 'karyawan',
                'jabatan'                => 'Business Development',
                'jabatan_lainnya'        => null,
                'status'                 => 'Outsource',
                'nomor_telepon'          => '081200000007',
                'jenis_kelamin'          => 'P',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Makassar',
                'tanggal_lahir'          => '1998-02-14',
                'status_pernikahan'      => 'Belum Menikah',
                'pendidikan_terakhir'    => 'S1',
                'pendidikan_terakhir_new'=> 'S1',
                'universitas'            => 'Universitas Hasanuddin',
                'jurusan'                => 'Komunikasi',
                'tahun_lulus'            => 2020,
                'alamat'                 => 'Jl. Penghibur No. 22, Makassar',
                'nik'                    => '7371010000000007',
                'npwp'                   => '12.345.678.9-012.006',
                'tanggal_bergabung'      => '2024-01-02',
                'nama_kontak_darurat'    => 'Dedi Lestari',
                'telepon_kontak_darurat' => '081200000017',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567896',
            ],

            // Karyawan 6 — Permanent — Video Editor
            [
                'nip'                    => 'EMP0006',
                'email'                  => 'fajar@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Fajar',
                'nama_belakang'          => 'Kurniawan',
                'nama_lengkap'           => 'Fajar Kurniawan',
                'role'                   => 'karyawan',
                'jabatan'                => 'Video Editor',
                'jabatan_lainnya'        => null,
                'status'                 => 'Permanent',
                'nomor_telepon'          => '081200000008',
                'jenis_kelamin'          => 'L',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Malang',
                'tanggal_lahir'          => '1994-11-08',
                'status_pernikahan'      => 'Menikah',
                'pendidikan_terakhir'    => 'SMK',
                'pendidikan_terakhir_new'=> 'SMK',
                'universitas'            => null,
                'jurusan'                => 'Multimedia',
                'tahun_lulus'            => 2013,
                'alamat'                 => 'Jl. Veteran No. 12, Malang',
                'nik'                    => '3573010000000008',
                'npwp'                   => '12.345.678.9-012.007',
                'tanggal_bergabung'      => '2022-06-15',
                'nama_kontak_darurat'    => 'Rani Kurniawan',
                'telepon_kontak_darurat' => '081200000018',
                'nama_bank'              => 'BSI',
                'nomor_rekening'         => '1234567897',
            ],

            // Karyawan 7 — Outsource — Lainnya (Custom: Office Assistant)
            [
                'nip'                    => 'EMP0007',
                'email'                  => 'nina@hris.com',
                'kata_sandi'             => Hash::make('password123'),
                'nama_depan'             => 'Nina',
                'nama_belakang'          => 'Anggraini',
                'nama_lengkap'           => 'Nina Anggraini',
                'role'                   => 'karyawan',
                'jabatan'                => 'lainnya',
                'jabatan_lainnya'        => 'Office Assistant',
                'status'                 => 'Outsource',
                'nomor_telepon'          => '081200000009',
                'jenis_kelamin'          => 'P',
                'agama'                  => 'Islam',
                'tempat_lahir'           => 'Denpasar',
                'tanggal_lahir'          => '1999-08-20',
                'status_pernikahan'      => 'Belum Menikah',
                'pendidikan_terakhir'    => 'SMA/MA',
                'pendidikan_terakhir_new'=> 'SMA/MA',
                'universitas'            => null,
                'jurusan'                => 'IPS',
                'tahun_lulus'            => 2017,
                'alamat'                 => 'Jl. Diponegoro No. 5, Denpasar',
                'nik'                    => '5171010000000009',
                'npwp'                   => '12.345.678.9-012.008',
                'tanggal_bergabung'      => '2024-03-01',
                'nama_kontak_darurat'    => 'Wayan Anggraini',
                'telepon_kontak_darurat' => '081200000019',
                'nama_bank'              => 'Mandiri',
                'nomor_rekening'         => '9876543210',
            ],
        ];

        foreach ($karyawanData as $data) {
            Karyawan::create($data);
        }
    }
}
